---
- hosts: cloud
  sudo: yes

  tasks:
    - name: install python3
      apt: name={{item}} state=installed
      with_items:
        - python3
        - python3-pip
    - name: install tweepy module
      shell: pip3 install tweepy

    - name: install jsonpickle module
      shell: pip3 install jsonpickle

    - name: install couchdb module
      shell: pip3 install couchdb